name: Terraform Deploy Reusable Workflow

# the workflow is called in a caller workflow
on:
  workflow_call:
    inputs:
      environment:
        description: Environment to run against
        type: string
        required: true
      nickname:
        description: Nickname of the project. Must be lowercase chars
        type: string
        required: true
      packages-directory:
        description: Where terraform script to build the packages (zip files)
        type: string
        required: false
      tf-version:
        description: Terraform version
        type: string
        required: false
        default: 1.4.2
      working-directory:
        description: Terraform working directory
        type: string
        required: true

jobs:
  plan:
    uses: ./.github/workflows/terraform-plan-reusable.yaml
    secrets: inherit
    with:
      environment: ${{ inputs.environment }}
      nickname: ${{ inputs.nickname }}
      packages-directory: ${{ inputs.packages-directory }}
      working-directory: ${{ inputs.working-directory }}

  apply:
    needs: [plan]
    if: ${{ needs.plan.outputs.tfplanExitCode == 2 }}
    uses: ./.github/workflows/terraform-apply-reusable.yaml
    secrets: inherit
    with:
      environment: ${{ inputs.environment }}
      nickname: ${{ inputs.nickname }}
      working-directory: ${{ inputs.working-directory }}
      packages-directory: ${{ inputs.packages-directory }}
