name: Terraform Deploy Reusable Workflow

# the workflow is called in a caller workflow
on:
  workflow_call:
    inputs:
      environment:
        description: Environment to run against
        type: string
        required: true
      nickname:
        description: Nickname of the project. Must be lowercase chars
        type: string
        required: true
      packages-directory:
        description: Where terraform script to build the packages (zip files)
        type: string
        required: false
      tf-version:
        description: Terraform version
        type: string
        required: false
        default: 1.4.2
      working-directory:
        description: Terraform working directory
        type: string
        required: true

env:
  # Variables & Secrets from GitHub Environment
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_ACCOUNT: ${{ vars.AWS_ACCOUNT }}
  AWS_REGION: ${{ vars.AWS_REGION }}
  STATE_BUCKET: ${{ vars.STATE_BUCKET }}
  # Inputs parameters
  ENVIRONMENT: ${{ inputs.environment }}
  NICKNAME: ${{ inputs.nickname }}
  TF_VERSION: ${{ inputs.tf-version }}
  WORKING_DIRECTORY: ${{ inputs.working-directory }}

jobs:
  plan:
    uses: ./.github/workflows/terraform-plan-reusable.yaml
    with:
      environment: ${{ inputs.environment }}
      nickname: lambda-layers
      working-directory: lambda-layers
      packages-directory: lambda-layers/build

  apply:
    needs: [terraform-plan]
    if: ${{ needs.plan.outputs.tfplanExitCode == 2 }}
    uses: ./.github/workflows/terraform-apply-reusable.yaml
    with:
      environment: ${{ inputs.environment }}
      nickname: lambda-layers
      working-directory: lambda-layers
      packages-directory: lambda-layers/build
